spring:
  application:
    name: NHN Academy - Spring Boot JPA
  datasource:
    url: jdbc:mysql://127.0.0.1/nhn_academy_31
    username: root
    password: sung2561
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace
